(defun do-nothing() (interactive))

(defun copy-whole-line-as-kill()
  (interactive)
  (save-excursion
    (beginning-of-line)
    (set-mark (point))
    (end-of-line)
    (copy-region-as-kill (region-beginning) (region-end))
    (pop-mark)))

(defun newline-no-disturb()
  (interactive)
  (end-of-line)
  (newline-and-indent))

(defun edit/insert-before()
  (interactive)
  (modal/into-insert-mode))

(defun edit/insert-after()
  (interactive)
  (forward-char)
  (modal/into-insert-mode))

(defun edit/insert-beginning-of-line()
  (interactive)
  (beginning-of-line-text)
  (modal/into-insert-mode))

(defun edit/insert-end-of-line()
  (interactive)
  (end-of-line)
  (modal/into-insert-mode))

(defun edit/insert-newline()
  (interactive)
  (newline-no-disturb)
  (modal/into-insert-mode))

(defun edit/yank-beg-newline()
  (interactive)
  (newline-no-disturb)
  (beginning-of-line)
  (yank))

(defun edit/replace-char()
  (interactive)
  (delete-char 1)
  (modal/into-insert-mode))

(defun edit/replace-line()
  (interactive)
  (kill-whole-line)
  (newline)
  (previous-line)
  (modal/into-insert-mode))

(defun edit/set-region()
  (interactive)
  (set-mark (point))
  (modal/into-region-mode))

(defun edit/set-region-line()
  (interactive)
  (beginning-of-line)
  (edit/set-region)
  (next-line)
  (beginning-of-line))

(defun edit/kill-region()
  (interactive)
  (kill-region (region-beginning) (region-end))
  (modal/into-normal-mode))

(defun edit/copy-region-as-kill()
  (interactive)
  (copy-region-as-kill (region-beginning) (region-end))
  (modal/into-normal-mode))

(defun edit/yank-replace-region()
  (interactive)
  (delete-region (region-beginning) (region-end))
  (yank)
  (modal/into-normal-mode))

(defun edit/replace-region()
  (interactive)
  (kill-region (region-beginning) (region-end))
  (modal/into-normal-mode)
  (modal/into-insert-mode))

(defun edit/set-rectangle()
  (interactive)
  (rectangle-mark-mode 1)
  (modal/into-rectangle-mode))

(defun edit/kill-rectangle()
  (interactive)
  (kill-rectangle (region-beginning) (region-end))
  (modal/into-normal-mode))

(defun edit/copy-rectangle-as-kill()
  (interactive)
  (copy-rectangle-as-kill (region-beginning) (region-end))
  (modal/into-normal-mode))

(defun edit/replace-rectangle()
  (interactive)
  (replace-rectangle (region-beginning) (region-end) (read-from-minibuffer "Text: "))
  (modal/into-normal-mode))

(defun edit/yank-replace-rectangle()
  (interactive)
  (replace-rectangle (region-beginning) (region-end) (current-kill 0))
  (modal/into-normal-mode))

(defun edit/kill-inside-word()
  (interactive)
  (forward-char)
  (backward-word)
  (kill-word nil))

(defun motion/inside-word()
  (interactive)
  (forward-char)
  (backward-word)
  (set-mark (point))
  (forward-word)
  (modal/into-region-mode))

(defun motion/inside-surround(char1 char2)
  (interactive)
  (forward-char)
  (search-backward char1)
  (forward-char)
  (set-mark (point))
  (search-forward char2)
  (backward-char)
  (modal/into-region-mode))    

(defun mark/insert-mark()
  (interactive)
  (insert "{[><]}"))

(defun mark/next-mark()
  (interactive)
  (search-forward "{[><]}")
  (search-backward "{")
  (set-mark (point))
  (search-forward "}")
  (delete-region (region-beginning) (region-end))
  (modal/into-insert-mode))
