;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	))

(setq mc/cmds-to-run-once
      '(
	hydra-multiple-cursors/ignore
	hydra-multiple-cursors/mc/add-cursor-on-click
	hydra-multiple-cursors/mc/edit-lines-and-exit
	hydra-multiple-cursors/mc/mark-next-like-this
	hydra-multiple-cursors/nil
	))
